### ISSUE TITLE
Contributor-hosted Windows RTX runner: restore installer releases + runtime verify (#38 hand-off)

### ISSUE THREAD

**Issue by opariffazman** [officialdad/camera-on-screen#48]
Hand-off brief for a contributor with a **Windows 10/11 x64 machine + NVIDIA RTX GPU** willing to host the project's Windows release runner. Everything below is scripted/runbooked — **fastest path: clone the repo on that machine, open a Claude Code session, and point it at this issue**; it can drive the whole setup. Runbook: `docs/ci/self-hosted-runner.md`; background: CLAUDE.md sections *Toolchain*, *CO-VERSION*, *Stage + Bundler*, *Installer*, *CI/CD*.

## Why

Windows PR-CI compile coverage is back on hosted runners (PR #45), but the **installer release job** (`release.yml` `release-windows`) needs real Windows + RTX: its verify gate (`verify-bundle.ps1`) runtime-loads both Maxine effects from the produced bundle. The dev box is Linux-only (single GPU, no passthrough option); current fallback is dual-booting on release day (#38).

## What the machine needs

- RTX GPU, Turing or newer (bundle ships sm75/86/89/100 engines), NVIDIA driver ≥ 528.24
- ~30 GB free disk (SDK trees + stage + builds)
- VS2022 **Build Tools** + MSVC v143, .NET 8 SDK, Inno Setup 6 (`winget install JRSoftware.InnoSetup`) — no full Visual Studio needed
- Free NVIDIA NGC account + personal API key (`NGC_CLI_API_KEY`) for fetching Maxine runtimes/engines
- Optional (FRUC in shim builds): NVIDIA Optical Flow SDK 5.0.7 (developer-program download) + CUDA toolkit for `cuda.lib`

## Setup outline

1. Toolchain install (above).
2. Reconstruct SDK/build inputs: VFX 1.2.0.0 + AR 1.1.1.0 (AR = GitHub `NVIDIA/MAXINE-AR-SDK` clone; VFX runtimes/engines from NGC via `scripts/fetch-maxine-engines.ps1`).
3. Assemble the co-versioned runtime stage ONCE: `scripts/assemble-maxine-stage.ps1` → set `COS_MAXINE_STAGE` for the runner (this is the only NGC-key step; the key stays on the contributor's box).
4. Local dry run: `scripts/build-installer.ps1 -DryRun`, then full build + `scripts/verify-bundle.ps1` (both effects must load with `COS_*` unset).
5. Register a GitHub Actions self-hosted runner (registration token from maintainer), labels `[self-hosted, windows, rtx]`, installed as a service. **NETWORK SERVICE gotchas are documented**: env vars go in `C:\actions-runner\.env`, service restart required after changes, no access to user-profile paths — SDKs live under the runner tree.
6. Maintainer dispatches `release.yml` → `release-windows` on the next `v*` tag; job builds installer → runtime verify gate → uploads to the GitHub release.

## Security / trust notes (maintainer + contributor read this)

- The runner is referenced ONLY by `release-windows`, which is `workflow_dispatch`-only — no `pull_request` workflow targets the `[self-hosted, windows, rtx]` labels, so fork PRs can never schedule jobs onto the contributor's machine. Keep it that way when touching workflows.
- Repo Actions settings should keep "require approval for outside collaborators' workflow runs" enabled (default).
- Trust is mutual and real: release binaries get BUILT on the contributor's hardware — the maintainer must trust the host, and the contributor accepts a service account running GitHub-dispatched jobs. Run the runner under a non-admin account.
- The runner machine also unlocks the rest of #38 when present: full Windows PR-CI on real SDK trees, FRUC-enabled builds, and #24's WinUI runtime verify.

Related: #38 (parent), #46/#47 (CI hardening), #24 (Windows ONNX runtime verify deferred here), #25.

🤖 Generated with [Claude Code](https://claude.com/claude-code)

**Comment by Lexxick** [comment]
## NGC unblocked — full pipeline green on sm86, installer + verify gate proven

Picking up from my [Aug 2 comment](https://github.com/officialdad/camera-on-screen/issues/48#issuecomment-5155327553). Headline: **the 402 blocker is solved, and the brief's premise was right after all** — a free NGC account *does* reach `nvidia/maxine`. My "this appears to be stale" conclusion was wrong, and the reason is worth recording because it is indistinguishable from a paywall.

### The 402 was a key-scope gotcha, not an entitlement

The personal API key must be generated with **NGC Catalog** ticked under *Services Included*. A key created without that scope authenticates perfectly — `users/me` and `orgs` return 200, and public teams like `nvidia/tao` work end-to-end — but returns **402 Payment Required** on every `nvidia/maxine` surface: every model, every version, every OS, including retired lines. That blanket-402-across-a-whole-team shape is what led me to read it as a subscription check.

Regenerating the key with Catalog scope cleared all of it at once: 7 lib/sdk-core packages and all 16 per-arch engine packages. **No NVAIE subscription, no Developer Program enrollment, no EULA click-through.** Nothing in the brief's prerequisites needs changing — `hasSignedNvidiaEULA: false` on the account was a red herring.

### Steps 2–4 complete and verified

| Path | What | Size |
|---|---|---|
| `_sdk\maxine-dl\` | NGC archive, 67 files, every one sha256-verified against `MANIFEST.tsv` | 3.43 GB |
| `_sdk\maxine-sdk\{VideoFX,ARSDK,ar-feature-libs}` | extracted VFX 1.2.0.0 + AR 1.1.1.0 trees + 3 gaze feature libs | 3.95 GB |
| `_sdk\maxine-stage\` | assembled co-versioned stage: 28 DLLs, 60 engines, 6 licenses (94 files) | 2.6 GB |
| `dist\stage\maxine\` | pruned bundle: 22 DLLs, 36 engines (8 vfx + 28 ar) | |
| `dist\CameraOnScreen-Setup-0.0.0-dev-x64.exe` | the deliverable | 974 MB |

`verify-bundle.ps1` against the bundled `maxine\` with `COS_*` cleared:

```
VFX  Probe: AVAILABLE (GreenScreen available)
AR   Probe: AVAILABLE (GazeRedirection available)
bundle verify OK -- both Maxine effects load from dist\stage\maxine
```

This box is **sm86**, the one arch CLAUDE.md calls verified on real silicon, so this gate exercises the engines that actually matter rather than a best-effort arch.

Build timing for release-day budgeting: shim 10.8s, dotnet 34.9s, bundle 1.8s, **ISCC 331.7s** — the installer compile dominates; budget ~6.5 min.

### Three real bugs in the Windows release gate

All three are Windows-side rot that #38's parked CI let through. Fixes are on `fix/windows-release-gate` (5 commits, pushed, rebased onto `v0.12.0`):

**1. `matte_ops.cpp` missing from 3 smoke build scripts.** `aigs.cpp` has referenced `matte::` symbols since the ONNX green-screen split (#24). `shim.vcxproj` and the Linux `CMakeLists.txt` both list it; only the smoke scripts were missed. The verify gate could not even link — 4 unresolved externals.

**2. `verify-bundle.ps1` leaked `COS_VFX_SDK_DIR` into the probe run.** It sets the var so the probe can *compile* against SDK headers, then never clears it. `vfx_paths.cpp` resolves `COS_VFX_SDK_DIR` → `<sdk>\bin\models` **above** the app-relative `maxine\` tier, and that directory is empty — engines ship only from NGC, never inside an SDK tree.

> This is the serious one. On any machine that can build the shim — i.e. every release host, since `.env` sets that var — **the gate was never testing the bundled VFX tier at all.** AR is immune because its resolver has no `SDK_DIR` tier, which is exactly why the symptom looked like a bad bundle rather than a bad gate. Fix: clear `COS_*_SDK_DIR` alongside the `RUNTIME` vars before the probe runs; they are compile-time only.

**3. `gpu_mem.cpp` missing from all 4 smoke builds — introduced by #69, found today.** The VRAM gate made `Aigs::Start`, `EyeContact::Start`, `Fruc::Start` and `cos_query_capabilities` call `gpumem::CanLoad`. `gpu_mem.cpp` is compiled by `shim.vcxproj` and `CMakeLists.txt`, but no smoke recipe lists it:

```
aigs.obj : error LNK2019: unresolved external symbol gpumem::CanLoad
                          referenced in function Aigs::Start
eyecontact.obj : error LNK2001: (same symbol)
fatal error LNK1120: 1 unresolved externals
```

Same failure mode as bug 1, one release later — the gate goes down before it can probe anything. This is a recurring shape: **the smoke build scripts are a fourth build system that nothing enforces.** Worth considering whether `build_bundle_probe.bat` should derive its source list from the vcxproj, or whether CI should compile the probe on the hosted Windows job so the drift is caught at PR time instead of on release day.

The green result above is from *after* all three fixes, so it is a genuine pass and not a gate that stopped checking.

### Two asks

**(a) May I open a PR for `fix/windows-release-gate`?** I withdrew #68 for lacking your sign-off and don't want to repeat that. Branch: https://github.com/officialdad/camera-on-screen/tree/fix/windows-release-gate · [compare](https://github.com/officialdad/camera-on-screen/compare/main...fix/windows-release-gate)

```
d22deab docs: correct the stale co-version target in the NGC probe
e8403a6 docs: record the PowerShell 7 install traps for the Windows RTX runner
880adc0 fix: link gpu_mem.cpp into the four Maxine smoke builds
e6ba416 fix: repair the Windows bundle verify gate (link + tier resolution)
8e0283e fix: make scripts/*.ps1 parse on Windows PowerShell 5.1 (ASCII only)
```

Bugs 2 and 3 affect the release gate on *any* Windows host, so they're worth landing regardless of what happens with the runner.

**(b) A self-hosted runner registration token**, labels `[self-hosted, windows, rtx]` (repo Settings → Actions → Runners → New self-hosted runner). Everything else for step 5 is staged: runner 2.336.0 extracted and hash-verified, `C:\actions-runner\.env` written with all three `COS_*` vars pointing at the real SDK trees + stage, ACLs checked for `NETWORK SERVICE`, PowerShell 7.6.4 installed machine-wide. The token is short-lived (~1 h), so send it when you're ready and I'll register immediately. The `svc install` / `svc start` step needs an elevated shell, which I'll run by hand.

### Smaller notes

- **Retracting my Finding 3.** The repo's SDK references are already correct (`NVIDIA-Maxine/Maxine-{VFX,AR}-SDK`); the single old-name hit is a spec doc describing the dead repo historically. Note the **issue body above still says `NVIDIA/MAXINE-AR-SDK`** — worth an edit.
- **Finding 2 (`pwsh`) is now handled**, and the runbook gained the PowerShell prerequisite it never had, plus both install traps: `winget install Microsoft.PowerShell --scope machine` resolves to the MSIX bundle and dies at 92% on Win10 (`0x8a150113`, and MSIX lands per-user under `WindowsApps` where `NETWORK SERVICE` can't reach it), and the MSI silently needs `ADD_PATH=1` — component `SetPath` is conditioned on it with no default, so the interactive UI ticks it but `/qn` does not, leaving `pwsh` off `PATH` while everything looks installed.
- **Maxine NIM evaluated and rejected** as an alternative to the SDK route: Docker/gRPC only, no native DLLs. It would break the in-process shim, the "no NVIDIA account for end users" contract, and `verify-bundle.ps1`.
- **The installer ships without FRUC.** `COS_FRUC_SDK_DIR` is unset — the Optical Flow SDK isn't on this box and it's a separate DesignWorks-licensed download, not NGC Maxine. The manifest lists `NvOFFRUC.dll` + `cudart64_110.dll` as `OptionalDlls`, so the bundle succeeds and frame interpolation is simply unavailable. **Do you want the first Windows release to ship without frame interpolation, or should I fetch the Optical Flow SDK first?**
- **Two caveats on the proven run:** the version was `0.0.0-dev` (the real one comes from the tag), and the gate verifies the *staging* bundle, not the installed output — by design, but installing the `.exe` and watching the overlay in a recorder is still an unexercised human gate.
- Also noticed, not fixed: `native/shim/smoke/aigs_smoke.cpp` is stale beyond its build comment — it calls `Aigs::ProcessFrame(bgra, W, H)` against a signature that's taken `(bgra, W, H, expand, feather)` since the expand/feather work, so it can't compile. Left alone deliberately; say the word if you want it revived or deleted.

<sub>Box: Win10 19045 x64, RTX 3050 Ti Laptop (sm86), driver 610.74.</sub>

**Comment by Lexxick** [comment]
Done — Windows installer releases are back.

- Runner `win-rtx3050ti` registered on this repo as a service (`NETWORK SERVICE`, labels `self-hosted, Windows, X64, rtx`).
- Gate fixes merged in #70, Windows `create || upload` fallback in #71.
- `v0.12.1` tagged and `release-windows` dispatched: [run 35302886544](https://github.com/officialdad/camera-on-screen/actions/runs/35302886544), 10 min 13 s, all steps green — `Check Maxine stage` (the `.env`-reaches-the-service proof), `VFX Probe: AVAILABLE`, `AR Probe: AVAILABLE`, `bundle verify OK` from the bundled tier on sm86.
- `CameraOnScreen-Setup-0.12.1-x64.exe` is on the [v0.12.1 release](https://github.com/officialdad/camera-on-screen/releases/tag/v0.12.1).

Docs/runbook catch-up is #72. The two things the pipeline doesn't cover — a human smoke test of the shipped exe, and FRUC being absent from this bundle — are #73.

@opariffazman two items on your side, neither urgent: GitHub auto-deleted `cachyos-rtx3090` (offline >14 days) — re-run `config.sh` and I can mint you a token, I have admin now. Then *Re-run all jobs* on the cancelled tag-push run [35302861401](https://github.com/officialdad/camera-on-screen/actions/runs/35302861401) to attach the Linux tarball to v0.12.1 (I had to cancel it: it held the release concurrency group and blocked the Windows dispatch — documented in #72).
